//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_SadrievRadisDanisovich.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Id { get; set; }
        public Nullable<int> Id_Tournament { get; set; }
        public Nullable<int> Id_Member1 { get; set; }
        public Nullable<int> Id_Member2 { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> Id_Winner { get; set; }
    
        public virtual TornamentMembers TornamentMembers { get; set; }
        public virtual TornamentMembers TornamentMembers1 { get; set; }
        public virtual TornamentMembers TornamentMembers2 { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
