//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_SadrievRadisDanisovich.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDB_421_SadrievRadisDanisovichEntities : DbContext
    {
        public TournamentDB_421_SadrievRadisDanisovichEntities()
            : base("name=TournamentDB_421_SadrievRadisDanisovichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievments> Achievments { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MembersCrew> MembersCrew { get; set; }
        public virtual DbSet<PlayingRole> PlayingRole { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TornamentMembers> TornamentMembers { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<TournamentCategory> TournamentCategory { get; set; }
        public virtual DbSet<TournamentCriterion> TournamentCriterion { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
